config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'

  get 'relationships/create'

  get 'relationships/destroy'

  resources :users, only: [:index, :edit]
  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :blogs do
    resources :comments
    post :confirm, on: :collection
  end

  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end

  root 'top#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at:"/letter_opener"
  end

  resources :poems, only: [:index, :show]

end

app/models/poem.rb
#class Poem < ActiveRecord::Base
#class Poem < ActiveResource::Base
#  self.site = "https://stormy-eyrie-30619.herokuapp.com"
class Poem
  include Her::Model
end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController
  before_action :set_poem, only: [:show]

  def index
    @poems = Poem.all
  end

  def show
  end

private
  def set_poem
    @poem = Poem.find(params[:id])
  end

end

app/helpers/poems_helper.rb
module PoemsHelper
end

app/views/poems/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <p><%= notice %></p>
    <h1>ポエム一覧</h1>

    <% @poems.each do |poem| %>
      <div class="row">
        <h4><strong><%= poem.title %></strong></h4>
        <p><%= poem.content %></P>
        <%= link_to "Show", poem_path(poem.id), class: 'btn btn-sm btn-info' %>
      </div>
    <% end %>
  </div>
</div>

app/views/poems/show.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <p><%= notice %></p>
    <h1>ポエム詳細</h1>

    <%= form_for(@poem) do |f| %>
      <div class="row">
        <h4><strong><%= @poem.title %></strong></h4>
        <p><%= @poem.content %></P>
        <%= link_to "戻る", poems_path, class: 'btn btn-default' %>
      </div>
    <% end %>
  </div>
</div>